language: ruby
rvm:
  - 2.6.0
  - 2.5.0
  - 2.4.0
branches:
  only: master
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --jobs=3 --retry=3 --deployment
- yarn install
script:
- yarn test
cache:
- bundler
- yarn
